spring:
  config:
    import: optional:application-secret.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/seatlock
    username: seatlock
    password: seatlock
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
kopis:
  service-key: ${KOPIS_SERVICE_KEY}